### ISSUE TITLE
Command "repo" missing on Ubuntu 15.10

### ISSUE THREAD

**Issue by EpicLPer** [ResurrectionRemix/ResurrectedScripts#1]
The command "repo" is not standard in Ubuntu and needs to be added manually.

Here's how to do it, please add these steps to your script: http://source.android.com/source/downloading.html (look at _Installing Repo_)

**Comment by Furrydaus** [comment]
Hi @EpicLPer,

You do realise that repo is installed and updated direct from google from lines 81-87 in the setup script right? To my knowledge 15.10 still works the same way as 14.04 LTS.

Regards,
Furrydaus

**Comment by EpicLPer** [comment]
Whoops... Well, I let the script run through and it stopped right at the first repo command since it reported it as missing, weird.

**Comment by Furrydaus** [comment]
I'll check on the issue with my laptop tomorrow morning. Didn't have anything wrong being pointed out on my end. Nonetheless thank you for reporting the issue.

Also, which script are you referring to?

**Comment by EpicLPer** [comment]
Oh, sorry, the setup.sh one. I tried it on a freshly installed Ubuntu 15.10 x64 Virtual Machine and there it failed until I ran the script to download and add it to the PATH manually.

**Comment by Furrydaus** [comment]
Hi @EpicLPer 

Thanks for notifying of the issue. it has now been fixed by the latest commit :)

Regards,
Firdaus

**Comment by EtienneBruines** [comment]
> You do realise that repo is installed and updated direct from google from lines 81-87 in the setup script right? 

I would like to comment that this only works, when `$home/bin` is part of your `$PATH`, since that's where it's installed.
