### ISSUE TITLE
For freshly installed Ubuntu Systems: Ask user to set git E-Mail and Name

### ISSUE THREAD

**Issue by EpicLPer** [ResurrectionRemix/ResurrectedScripts#2]
In order for the initial setup script to run through on freshly installed (Ubuntu) systems it'd be nice for the script to ask the user if he already set the git Name and E-Mail address. Else the script will get stuck there and won't download anything.

I know that normal git-users already have this set and will probably think to set it once they installed a new Ubuntu system, however as I'm speaking for the beginners here (since I am one :) ) it would be nice for the setup-script here to ask that first since I forgot it and had to re-run the script after the error message was popping up.

Commands are:

```
git config --global user.email "*email*"
git config --global user.name "*name*"
```

Thanks a lot!

**Comment by Furrydaus** [comment]
Hi @epicLPer ,

Mainly the concern is that we do not want the script to be easy to use. We want there to be a skill/knowledge ceiling. If we are to spoonfeed every newbie, we will end up having a community full of uneducated maintainers who do not know what they are doing. Hope you understand this.

Regards,
Firdaus

**Comment by EpicLPer** [comment]
Yes, I do know. But I mainly tried to set this up to compile for a device that's "officially" maintained by you guys, however there was no ROM compiled for it the past few days. It's probably a bit low on your list of devices to compile. It would be "amami" if you're interested ;)

**Comment by Furrydaus** [comment]
Sadly, Amami seems to have been dropped by the maintainer that was tied to it. We can't do much to help maintain it but I may be able to build for Amami if I have the time but might be difficult considering I've got other things to handle.

If you'd like to support it, be sure to readup more before building and check if CM has a maintainer. If they do, contact him/her and ask them if they are going to continue supporting the device.

If not, you'd be left with a old device code that might not work with future versions of android.

Regards
Firdaus

**Comment by EpicLPer** [comment]
Yeah, that's the problem right now. The last version that was built for Amami (5.6.4) has a few bugs regarding brightness, battery, deep sleep mode and so on and I hoped a new compiled version of 5.6.6 might solve this.

Then again, yeah, I only "tried" it and was getting so far as reporting these bugs right now :P I wasn't actually getting to the point of trying to build the ROM itself due to constantly getting different errors and so on. I'll try again when I have time :)

**Comment by Furrydaus** [comment]
Most of those bugs are usually tied to your device source code. Battery problems might be tied to RR. Either way good luck :)
