### ISSUE TITLE
On what Ubuntu Version does this script work?

### ISSUE THREAD

**Issue by lfuelling** [ResurrectionRemix/ResurrectedScripts#3]
I tried running the setup script on Debian 8 & 7. The packages that couldn't be found are:
- liblz4-\* 
- binutils-static
- libgcc1
- phablet-tools
- android-tools-adb

The unavailable packages causing apt to exit and the setup script to fail.

I also tried Ubuntu 15.10 & 15.04, the packe `libgcc1` was the only one not found there.

Which version of Ubuntu/Debian do you use to build RR?

Thanks in advance.

**Comment by benbois** [comment]
Hi, I'm using Linux Mint 17.3 - 64bits Mate edition.

**Comment by lfuelling** [comment]
Thanks for the info. I'll try this out and get back here in a bit.

**Comment by akhilnarang** [comment]
Ubuntu 14.04 LTS trusty tahr
also works on linux mint rosa 17.3

**Comment by lfuelling** [comment]
Thank you very much. :smile:
